// =========================================
// BASE DE DATOS DE EJERCICIOS
// 50 ejercicios esenciales para el sistema de rutinas
// =========================================

import { db } from './firebase-config.js';
import { collection, doc, setDoc, getDocs, getDoc } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js';

// =========================================
// BASE DE DATOS DE 50 EJERCICIOS
// =========================================

export const EXERCISES_DB = [
    // ========== PECHO (6) ==========
    {
        id: 'press_banca',
        nombre: 'Press de banca',
        nombreEN: 'Bench Press',
        alias: ['press banca', 'bench press', 'press plano'],
        grupoMuscular: 'pecho',
        musculosSecundarios: ['triceps', 'hombros'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Ejercicio fundamental para desarrollo de pecho, fuerza general y masa muscular.',
        popularidad: 95,
        orden: 1,
        activo: true
    },
    {
        id: 'press_inclinado',
        nombre: 'Press inclinado',
        nombreEN: 'Incline Bench Press',
        alias: ['press inclinado', 'incline press', 'press inclinado barra'],
        grupoMuscular: 'pecho',
        musculosSecundarios: ['hombros', 'triceps'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Enfatiza la parte superior del pecho y hombros frontales.',
        popularidad: 90,
        orden: 2,
        activo: true
    },
    {
        id: 'press_declinado',
        nombre: 'Press declinado',
        nombreEN: 'Decline Bench Press',
        alias: ['press declinado', 'decline press'],
        grupoMuscular: 'pecho',
        musculosSecundarios: ['triceps'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Trabaja la parte inferior del pecho.',
        popularidad: 75,
        orden: 3,
        activo: true
    },
    {
        id: 'press_mancuernas',
        nombre: 'Press con mancuernas',
        nombreEN: 'Dumbbell Press',
        alias: ['press mancuernas', 'dumbbell press', 'press plano mancuernas'],
        grupoMuscular: 'pecho',
        musculosSecundarios: ['triceps', 'hombros'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Mayor rango de movimiento y trabajo de estabilización.',
        popularidad: 88,
        orden: 4,
        activo: true
    },
    {
        id: 'aperturas_mancuernas',
        nombre: 'Aperturas con mancuernas',
        nombreEN: 'Dumbbell Flyes',
        alias: ['aperturas', 'flyes', 'aperturas pecho'],
        grupoMuscular: 'pecho',
        musculosSecundarios: ['hombros'],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Estiramiento y contracción máxima del pecho.',
        popularidad: 85,
        orden: 5,
        activo: true
    },
    {
        id: 'fondos_paralelas',
        nombre: 'Fondos en paralelas',
        nombreEN: 'Dips',
        alias: ['fondos', 'dips', 'fondos pecho'],
        grupoMuscular: 'pecho',
        musculosSecundarios: ['triceps', 'hombros'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🤸',
        descripcion: 'Excelente para pecho inferior y tríceps.',
        popularidad: 82,
        orden: 6,
        activo: true
    },

    // ========== ESPALDA (8) ==========
    {
        id: 'dominadas',
        nombre: 'Dominadas',
        nombreEN: 'Pull-ups',
        alias: ['dominadas', 'pull ups', 'pullups'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['biceps', 'hombros'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'traccion',
        dificultad: 'avanzado',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏋️',
        descripcion: 'Rey de los ejercicios de espalda y fuerza relativa.',
        popularidad: 92,
        orden: 7,
        activo: true
    },
    {
        id: 'remo_barra',
        nombre: 'Remo con barra',
        nombreEN: 'Barbell Row',
        alias: ['remo barra', 'barbell row', 'remo'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['biceps', 'hombros'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏋️',
        descripcion: 'Desarrollo completo del grosor de la espalda.',
        popularidad: 89,
        orden: 8,
        activo: true
    },
    {
        id: 'peso_muerto',
        nombre: 'Peso muerto',
        nombreEN: 'Deadlift',
        alias: ['peso muerto', 'deadlift', 'peso muerto convencional'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['piernas', 'core', 'trapecio'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'avanzado',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏋️',
        descripcion: 'El ejercicio más completo, trabaja todo el cuerpo.',
        popularidad: 98,
        orden: 9,
        activo: true
    },
    {
        id: 'remo_mancuerna',
        nombre: 'Remo con mancuerna',
        nombreEN: 'Dumbbell Row',
        alias: ['remo mancuerna', 'remo unilateral'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['biceps', 'core'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏋️',
        descripcion: 'Permite aislar cada lado de la espalda.',
        popularidad: 86,
        orden: 10,
        activo: true
    },
    {
        id: 'jalon_pecho',
        nombre: 'Jalón al pecho',
        nombreEN: 'Lat Pulldown',
        alias: ['jalon', 'lat pulldown', 'jalon pecho'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['biceps'],
        tipo: 'compuesto',
        equipamiento: 'maquina',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏋️',
        descripcion: 'Excelente para desarrollar amplitud de espalda.',
        popularidad: 84,
        orden: 11,
        activo: true
    },
    {
        id: 'remo_cable',
        nombre: 'Remo en polea',
        nombreEN: 'Cable Row',
        alias: ['remo cable', 'cable row', 'remo sentado'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['biceps'],
        tipo: 'compuesto',
        equipamiento: 'cable',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏋️',
        descripcion: 'Tensión constante en toda la espalda.',
        popularidad: 80,
        orden: 12,
        activo: true
    },
    {
        id: 'pullover',
        nombre: 'Pullover',
        nombreEN: 'Dumbbell Pullover',
        alias: ['pullover', 'pullover mancuerna'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['pecho'],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏋️',
        descripcion: 'Expande la caja torácica y trabaja dorsales.',
        popularidad: 70,
        orden: 13,
        activo: true
    },
    {
        id: 'face_pulls',
        nombre: 'Face pulls',
        nombreEN: 'Face Pulls',
        alias: ['face pulls', 'facepulls', 'tirones cara'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['hombros'],
        tipo: 'aislamiento',
        equipamiento: 'cable',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏋️',
        descripcion: 'Crucial para salud de hombros y postura.',
        popularidad: 78,
        orden: 14,
        activo: true
    },

    // ========== PIERNAS (10) ==========
    {
        id: 'sentadilla',
        nombre: 'Sentadilla',
        nombreEN: 'Squat',
        alias: ['sentadilla', 'squat', 'sentadilla trasera'],
        grupoMuscular: 'piernas',
        musculosSecundarios: ['core', 'espalda'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'El rey de los ejercicios de pierna.',
        popularidad: 96,
        orden: 15,
        activo: true
    },
    {
        id: 'sentadilla_frontal',
        nombre: 'Sentadilla frontal',
        nombreEN: 'Front Squat',
        alias: ['sentadilla frontal', 'front squat'],
        grupoMuscular: 'piernas',
        musculosSecundarios: ['core'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'avanzado',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Mayor énfasis en cuádriceps y core.',
        popularidad: 78,
        orden: 16,
        activo: true
    },
    {
        id: 'peso_muerto_rumano',
        nombre: 'Peso muerto rumano',
        nombreEN: 'Romanian Deadlift',
        alias: ['peso muerto rumano', 'rdl', 'romanian deadlift'],
        grupoMuscular: 'piernas',
        musculosSecundarios: ['espalda', 'core'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Excelente para femorales y glúteos.',
        popularidad: 85,
        orden: 17,
        activo: true
    },
    {
        id: 'prensa',
        nombre: 'Prensa de piernas',
        nombreEN: 'Leg Press',
        alias: ['prensa', 'leg press', 'prensa piernas'],
        grupoMuscular: 'piernas',
        musculosSecundarios: [],
        tipo: 'compuesto',
        equipamiento: 'maquina',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Segura y efectiva para desarrollar piernas.',
        popularidad: 88,
        orden: 18,
        activo: true
    },
    {
        id: 'zancadas',
        nombre: 'Zancadas',
        nombreEN: 'Lunges',
        alias: ['zancadas', 'lunges', 'estocadas'],
        grupoMuscular: 'piernas',
        musculosSecundarios: ['core'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Trabajo unilateral y funcional de piernas.',
        popularidad: 82,
        orden: 19,
        activo: true
    },
    {
        id: 'bulgaro',
        nombre: 'Sentadilla búlgara',
        nombreEN: 'Bulgarian Split Squat',
        alias: ['bulgaro', 'sentadilla bulgara', 'split squat'],
        grupoMuscular: 'piernas',
        musculosSecundarios: ['core'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Excelente para glúteos y cuádriceps unilateral.',
        popularidad: 76,
        orden: 20,
        activo: true
    },
    {
        id: 'curl_femoral',
        nombre: 'Curl femoral',
        nombreEN: 'Leg Curl',
        alias: ['curl femoral', 'leg curl', 'curl piernas'],
        grupoMuscular: 'piernas',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'maquina',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Aislamiento directo de femorales.',
        popularidad: 80,
        orden: 21,
        activo: true
    },
    {
        id: 'extension_cuadriceps',
        nombre: 'Extensión de cuádriceps',
        nombreEN: 'Leg Extension',
        alias: ['extension cuadriceps', 'leg extension'],
        grupoMuscular: 'piernas',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'maquina',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Aislamiento directo de cuádriceps.',
        popularidad: 79,
        orden: 22,
        activo: true
    },
    {
        id: 'pantorrillas_pie',
        nombre: 'Elevación de pantorrillas de pie',
        nombreEN: 'Standing Calf Raise',
        alias: ['pantorrillas pie', 'calf raise', 'gemelos'],
        grupoMuscular: 'piernas',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'maquina',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Desarrollo de gemelos (gastrocnemio).',
        popularidad: 72,
        orden: 23,
        activo: true
    },
    {
        id: 'pantorrillas_sentado',
        nombre: 'Elevación de pantorrillas sentado',
        nombreEN: 'Seated Calf Raise',
        alias: ['pantorrillas sentado', 'seated calf'],
        grupoMuscular: 'piernas',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'maquina',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Trabaja el sóleo de las pantorrillas.',
        popularidad: 68,
        orden: 24,
        activo: true
    },

    // ========== HOMBROS (6) ==========
    {
        id: 'press_militar',
        nombre: 'Press militar',
        nombreEN: 'Overhead Press',
        alias: ['press militar', 'overhead press', 'press hombros'],
        grupoMuscular: 'hombros',
        musculosSecundarios: ['triceps', 'core'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦾',
        descripcion: 'Fundamental para desarrollo de hombros y fuerza.',
        popularidad: 91,
        orden: 25,
        activo: true
    },
    {
        id: 'press_arnold',
        nombre: 'Press Arnold',
        nombreEN: 'Arnold Press',
        alias: ['press arnold', 'arnold press'],
        grupoMuscular: 'hombros',
        musculosSecundarios: ['triceps'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦾',
        descripcion: 'Rotación que trabaja todos los deltoides.',
        popularidad: 75,
        orden: 26,
        activo: true
    },
    {
        id: 'elevaciones_laterales',
        nombre: 'Elevaciones laterales',
        nombreEN: 'Lateral Raises',
        alias: ['elevaciones laterales', 'lateral raises', 'pajaros laterales'],
        grupoMuscular: 'hombros',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦾',
        descripcion: 'Esencial para amplitud de hombros.',
        popularidad: 89,
        orden: 27,
        activo: true
    },
    {
        id: 'elevaciones_frontales',
        nombre: 'Elevaciones frontales',
        nombreEN: 'Front Raises',
        alias: ['elevaciones frontales', 'front raises'],
        grupoMuscular: 'hombros',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦾',
        descripcion: 'Trabaja el deltoides frontal.',
        popularidad: 73,
        orden: 28,
        activo: true
    },
    {
        id: 'pajaros',
        nombre: 'Pájaros',
        nombreEN: 'Rear Delt Flyes',
        alias: ['pajaros', 'rear delt', 'deltoides posterior'],
        grupoMuscular: 'hombros',
        musculosSecundarios: ['espalda'],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦾',
        descripcion: 'Crucial para deltoides posterior y postura.',
        popularidad: 81,
        orden: 29,
        activo: true
    },
    {
        id: 'remo_alto',
        nombre: 'Remo alto',
        nombreEN: 'Upright Row',
        alias: ['remo alto', 'upright row'],
        grupoMuscular: 'hombros',
        musculosSecundarios: ['trapecio'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦾',
        descripcion: 'Desarrollo de hombros y trapecios.',
        popularidad: 70,
        orden: 30,
        activo: true
    },

    // ========== BÍCEPS (5) ==========
    {
        id: 'curl_barra',
        nombre: 'Curl con barra',
        nombreEN: 'Barbell Curl',
        alias: ['curl barra', 'barbell curl', 'curl'],
        grupoMuscular: 'biceps',
        musculosSecundarios: ['antebrazos'],
        tipo: 'aislamiento',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Clásico para masa de bíceps.',
        popularidad: 90,
        orden: 31,
        activo: true
    },
    {
        id: 'curl_mancuernas',
        nombre: 'Curl con mancuernas',
        nombreEN: 'Dumbbell Curl',
        alias: ['curl mancuernas', 'dumbbell curl', 'curl alterno'],
        grupoMuscular: 'biceps',
        musculosSecundarios: ['antebrazos'],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Permite supinación completa y trabajo unilateral.',
        popularidad: 87,
        orden: 32,
        activo: true
    },
    {
        id: 'curl_martillo',
        nombre: 'Curl martillo',
        nombreEN: 'Hammer Curl',
        alias: ['curl martillo', 'hammer curl'],
        grupoMuscular: 'biceps',
        musculosSecundarios: ['antebrazos'],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Enfatiza braquial y braquiorradial.',
        popularidad: 84,
        orden: 33,
        activo: true
    },
    {
        id: 'curl_predicador',
        nombre: 'Curl predicador',
        nombreEN: 'Preacher Curl',
        alias: ['curl predicador', 'preacher curl', 'curl scott'],
        grupoMuscular: 'biceps',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Aislamiento estricto del bíceps.',
        popularidad: 76,
        orden: 34,
        activo: true
    },
    {
        id: 'curl_cable',
        nombre: 'Curl en polea',
        nombreEN: 'Cable Curl',
        alias: ['curl cable', 'cable curl', 'curl polea'],
        grupoMuscular: 'biceps',
        musculosSecundarios: ['antebrazos'],
        tipo: 'aislamiento',
        equipamiento: 'cable',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Tensión constante en todo el rango.',
        popularidad: 78,
        orden: 35,
        activo: true
    },

    // ========== TRÍCEPS (5) ==========
    {
        id: 'press_cerrado',
        nombre: 'Press banca agarre cerrado',
        nombreEN: 'Close Grip Bench Press',
        alias: ['press cerrado', 'close grip', 'press agarre cerrado'],
        grupoMuscular: 'triceps',
        musculosSecundarios: ['pecho'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'El mejor ejercicio para masa de tríceps.',
        popularidad: 85,
        orden: 36,
        activo: true
    },
    {
        id: 'fondos_triceps',
        nombre: 'Fondos para tríceps',
        nombreEN: 'Triceps Dips',
        alias: ['fondos triceps', 'tricep dips'],
        grupoMuscular: 'triceps',
        musculosSecundarios: ['pecho'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Excelente para desarrollo completo de tríceps.',
        popularidad: 82,
        orden: 37,
        activo: true
    },
    {
        id: 'extensiones_polea',
        nombre: 'Extensiones en polea',
        nombreEN: 'Cable Pushdown',
        alias: ['extensiones polea', 'pushdown', 'jalones triceps'],
        grupoMuscular: 'triceps',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'cable',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Aislamiento clásico de tríceps.',
        popularidad: 88,
        orden: 38,
        activo: true
    },
    {
        id: 'extensiones_frances',
        nombre: 'Extensiones francesas',
        nombreEN: 'Skull Crushers',
        alias: ['extensiones francesas', 'skull crushers', 'press frances'],
        grupoMuscular: 'triceps',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Gran estiramiento de la cabeza larga del tríceps.',
        popularidad: 79,
        orden: 39,
        activo: true
    },
    {
        id: 'patada_triceps',
        nombre: 'Patada de tríceps',
        nombreEN: 'Triceps Kickback',
        alias: ['patada triceps', 'kickback', 'extensiones traseras'],
        grupoMuscular: 'triceps',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Aislamiento del tríceps con contracción máxima.',
        popularidad: 72,
        orden: 40,
        activo: true
    },

    // ========== CORE (5) ==========
    {
        id: 'plancha',
        nombre: 'Plancha',
        nombreEN: 'Plank',
        alias: ['plancha', 'plank', 'plancha abdominal'],
        grupoMuscular: 'core',
        musculosSecundarios: ['hombros'],
        tipo: 'estatico',
        equipamiento: 'peso_corporal',
        mecanica: 'estatico',
        dificultad: 'principiante',
        tipoMedicion: 'tiempo',
        unidadPeso: 'segundos',
        icono: '🔥',
        descripcion: 'El mejor ejercicio para estabilidad del core.',
        popularidad: 92,
        orden: 41,
        activo: true
    },
    {
        id: 'crunches',
        nombre: 'Crunches',
        nombreEN: 'Crunches',
        alias: ['crunches', 'abdominales', 'crunch'],
        grupoMuscular: 'core',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'peso_corporal',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🔥',
        descripcion: 'Clásico para abdominales superiores.',
        popularidad: 85,
        orden: 42,
        activo: true
    },
    {
        id: 'elevacion_piernas',
        nombre: 'Elevación de piernas',
        nombreEN: 'Leg Raises',
        alias: ['elevacion piernas', 'leg raises', 'elevaciones'],
        grupoMuscular: 'core',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'peso_corporal',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🔥',
        descripcion: 'Excelente para abdomen inferior.',
        popularidad: 83,
        orden: 43,
        activo: true
    },
    {
        id: 'russian_twist',
        nombre: 'Russian twist',
        nombreEN: 'Russian Twist',
        alias: ['russian twist', 'giros rusos', 'twist'],
        grupoMuscular: 'core',
        musculosSecundarios: ['oblicuos'],
        tipo: 'aislamiento',
        equipamiento: 'peso_corporal',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🔥',
        descripcion: 'Trabaja oblicuos y rotación del core.',
        popularidad: 80,
        orden: 44,
        activo: true
    },
    {
        id: 'mountain_climbers',
        nombre: 'Mountain climbers',
        nombreEN: 'Mountain Climbers',
        alias: ['mountain climbers', 'escaladores'],
        grupoMuscular: 'core',
        musculosSecundarios: ['cardio'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🔥',
        descripcion: 'Combina core y cardio intenso.',
        popularidad: 78,
        orden: 45,
        activo: true
    },

    // ========== FULLBODY (5) ==========
    {
        id: 'burpees',
        nombre: 'Burpees',
        nombreEN: 'Burpees',
        alias: ['burpees', 'burpee'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['cardio'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🏃',
        descripcion: 'Ejercicio explosivo de cuerpo completo.',
        popularidad: 86,
        orden: 46,
        activo: true
    },
    {
        id: 'thruster',
        nombre: 'Thruster',
        nombreEN: 'Thruster',
        alias: ['thruster', 'thrusters'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['cardio'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'avanzado',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏃',
        descripcion: 'Sentadilla frontal + press en un movimiento.',
        popularidad: 75,
        orden: 47,
        activo: true
    },
    {
        id: 'clean_press',
        nombre: 'Clean & Press',
        nombreEN: 'Clean and Press',
        alias: ['clean press', 'cargada y press', 'clean and press'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['cardio'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'avanzado',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏃',
        descripcion: 'Movimiento olímpico de potencia total.',
        popularidad: 72,
        orden: 48,
        activo: true
    },
    {
        id: 'kettlebell_swing',
        nombre: 'Swing con kettlebell',
        nombreEN: 'Kettlebell Swing',
        alias: ['kettlebell swing', 'swing', 'balanceo kettlebell'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['cardio'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🏃',
        descripcion: 'Potencia de cadera y acondicionamiento.',
        popularidad: 81,
        orden: 49,
        activo: true
    },
    {
        id: 'farmers_walk',
        nombre: 'Farmer\'s walk',
        nombreEN: 'Farmer\'s Walk',
        alias: ['farmers walk', 'caminata granjero', 'paseo granjero'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['core', 'antebrazos'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'estatico',
        dificultad: 'principiante',
        tipoMedicion: 'distancia',
        unidadPeso: 'metros',
        icono: '🏃',
        descripcion: 'Fuerza de agarre y estabilidad total.',
        popularidad: 77,
        orden: 50,
        activo: true
    },
    // ========== ADICIONALES PECHO (5) ==========
    {
        id: 'press_mancuerna_inclinado',
        nombre: 'Press mancuerna inclinado',
        nombreEN: 'Incline Dumbbell Press',
        alias: ['press inclinado mancuernas', 'incline db press'],
        grupoMuscular: 'pecho',
        musculosSecundarios: ['hombros', 'triceps'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Enfoque en pecho superior con mayor rango de movimiento.',
        popularidad: 88,
        orden: 51,
        activo: true
    },
    {
        id: 'press_decline',
        nombre: 'Press decline',
        nombreEN: 'Decline Press',
        alias: ['press declinado', 'decline bench'],
        grupoMuscular: 'pecho',
        musculosSecundarios: ['triceps'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Énfasis en pecho inferior.',
        popularidad: 75,
        orden: 52,
        activo: true
    },
    {
        id: 'fondos_pecho',
        nombre: 'Fondos para pecho',
        nombreEN: 'Chest Dips',
        alias: ['dips pecho', 'chest dips', 'fondos inclinados'],
        grupoMuscular: 'pecho',
        musculosSecundarios: ['triceps', 'hombros'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Inclinarse adelante para enfatizar pecho.',
        popularidad: 84,
        orden: 53,
        activo: true
    },
    {
        id: 'pullover_mancuerna',
        nombre: 'Pullover con mancuerna',
        nombreEN: 'Dumbbell Pullover',
        alias: ['pullover', 'pull over'],
        grupoMuscular: 'pecho',
        musculosSecundarios: ['espalda', 'triceps'],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Expansión de caja torácica y pecho.',
        popularidad: 72,
        orden: 54,
        activo: true
    },
    {
        id: 'pec_deck',
        nombre: 'Pec deck (mariposa)',
        nombreEN: 'Pec Deck Machine',
        alias: ['mariposa', 'pec deck', 'chest fly machine'],
        grupoMuscular: 'pecho',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'maquina',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Aislamiento de pecho con movimiento controlado.',
        popularidad: 78,
        orden: 55,
        activo: true
    },
    // ========== ADICIONALES ESPALDA (6) ==========
    {
        id: 'peso_muerto_rumano',
        nombre: 'Peso muerto rumano',
        nombreEN: 'Romanian Deadlift',
        alias: ['rdl', 'romanian deadlift', 'rumano'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['isquiotibiales', 'gluteos'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Énfasis en cadena posterior y espalda baja.',
        popularidad: 89,
        orden: 56,
        activo: true
    },
    {
        id: 'remo_t_barra',
        nombre: 'Remo en T con barra',
        nombreEN: 'T-Bar Row',
        alias: ['t bar row', 'remo t', 'remo barra t'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['biceps'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Grosor de espalda media.',
        popularidad: 83,
        orden: 57,
        activo: true
    },
    {
        id: 'remo_maquina',
        nombre: 'Remo en máquina',
        nombreEN: 'Machine Row',
        alias: ['seated row machine', 'remo sentado máquina'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['biceps'],
        tipo: 'compuesto',
        equipamiento: 'maquina',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Seguro y efectivo para principiantes.',
        popularidad: 75,
        orden: 58,
        activo: true
    },
    {
        id: 'pulldown_agarre_cerrado',
        nombre: 'Pulldown agarre cerrado',
        nombreEN: 'Close Grip Pulldown',
        alias: ['jalón agarre cerrado', 'close grip lat pulldown'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['biceps'],
        tipo: 'compuesto',
        equipamiento: 'cable',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Mayor activación de dorsales bajos.',
        popularidad: 78,
        orden: 59,
        activo: true
    },
    {
        id: 'pull_ups_neutrales',
        nombre: 'Dominadas agarre neutral',
        nombreEN: 'Neutral Grip Pull-ups',
        alias: ['dominadas neutro', 'neutral pull ups'],
        grupoMuscular: 'espalda',
        musculosSecundarios: ['biceps'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Más cómodo para muñecas y hombros.',
        popularidad: 80,
        orden: 60,
        activo: true
    },
    {
        id: 'shrugs_barra',
        nombre: 'Shrugs con barra',
        nombreEN: 'Barbell Shrugs',
        alias: ['encogimientos barra', 'trapecio barra'],
        grupoMuscular: 'espalda',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Desarrollo de trapecios superiores.',
        popularidad: 76,
        orden: 61,
        activo: true
    },
    // ========== ADICIONALES PIERNAS (8) ==========
    {
        id: 'sentadilla_bulgara',
        nombre: 'Sentadilla búlgara',
        nombreEN: 'Bulgarian Split Squat',
        alias: ['bulgarian split squat', 'sentadilla split'],
        grupoMuscular: 'piernas',
        musculosSecundarios: ['gluteos'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Trabajo unilateral de cuádriceps y glúteos.',
        popularidad: 87,
        orden: 62,
        activo: true
    },
    {
        id: 'hip_thrust_barra',
        nombre: 'Hip thrust con barra',
        nombreEN: 'Barbell Hip Thrust',
        alias: ['hip thrust', 'empuje cadera'],
        grupoMuscular: 'piernas',
        musculosSecundarios: ['gluteos'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Mejor ejercicio para glúteos.',
        popularidad: 90,
        orden: 63,
        activo: true
    },
    {
        id: 'sentadilla_hack',
        nombre: 'Sentadilla hack',
        nombreEN: 'Hack Squat',
        alias: ['hack squat', 'sentadilla máquina hack'],
        grupoMuscular: 'piernas',
        musculosSecundarios: [],
        tipo: 'compuesto',
        equipamiento: 'maquina',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Seguro para espalda, enfoca cuádriceps.',
        popularidad: 79,
        orden: 64,
        activo: true
    },
    {
        id: 'peso_muerto_sumo',
        nombre: 'Peso muerto sumo',
        nombreEN: 'Sumo Deadlift',
        alias: ['sumo deadlift', 'peso muerto piernas abiertas'],
        grupoMuscular: 'piernas',
        musculosSecundarios: ['espalda', 'gluteos'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Menos estrés en espalda baja.',
        popularidad: 82,
        orden: 65,
        activo: true
    },
    {
        id: 'curl_nordico',
        nombre: 'Curl nórdico',
        nombreEN: 'Nordic Curl',
        alias: ['nordic hamstring curl', 'nórdico isquios'],
        grupoMuscular: 'piernas',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'peso_corporal',
        mecanica: 'traccion',
        dificultad: 'avanzado',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🦵',
        descripcion: 'Máxima activación de isquiotibiales.',
        popularidad: 85,
        orden: 66,
        activo: true
    },
    {
        id: 'goblet_squat',
        nombre: 'Sentadilla goblet',
        nombreEN: 'Goblet Squat',
        alias: ['goblet squat', 'sentadilla copa'],
        grupoMuscular: 'piernas',
        musculosSecundarios: ['core'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Excelente para aprender técnica.',
        popularidad: 74,
        orden: 67,
        activo: true
    },
    {
        id: 'buenos_dias',
        nombre: 'Buenos días',
        nombreEN: 'Good Mornings',
        alias: ['good mornings', 'good morning'],
        grupoMuscular: 'piernas',
        musculosSecundarios: ['espalda', 'isquiotibiales'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'avanzado',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🦵',
        descripcion: 'Fortalece cadena posterior.',
        popularidad: 68,
        orden: 68,
        activo: true
    },
    {
        id: 'step_ups',
        nombre: 'Step ups',
        nombreEN: 'Step Ups',
        alias: ['subidas cajón', 'step up'],
        grupoMuscular: 'piernas',
        musculosSecundarios: ['gluteos'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🦵',
        descripcion: 'Ejercicio funcional unilateral.',
        popularidad: 71,
        orden: 69,
        activo: true
    },
    // ========== ADICIONALES HOMBROS (6) ==========
    {
        id: 'press_arnold',
        nombre: 'Press Arnold',
        nombreEN: 'Arnold Press',
        alias: ['arnold press', 'press arnold mancuerna'],
        grupoMuscular: 'hombros',
        musculosSecundarios: ['triceps'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Mayor rango de movimiento para deltoides.',
        popularidad: 83,
        orden: 70,
        activo: true
    },
    {
        id: 'face_pulls',
        nombre: 'Face pulls',
        nombreEN: 'Face Pulls',
        alias: ['face pull', 'jalón cara'],
        grupoMuscular: 'hombros',
        musculosSecundarios: ['trapecio'],
        tipo: 'aislamiento',
        equipamiento: 'cable',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Salud de hombros y deltoides posteriores.',
        popularidad: 88,
        orden: 71,
        activo: true
    },
    {
        id: 'elevaciones_frontales_barra',
        nombre: 'Elevaciones frontales con barra',
        nombreEN: 'Barbell Front Raise',
        alias: ['front raise barra', 'elevación frontal barra'],
        grupoMuscular: 'hombros',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Aislamiento de deltoides frontales.',
        popularidad: 70,
        orden: 72,
        activo: true
    },
    {
        id: 'press_landmine',
        nombre: 'Press landmine',
        nombreEN: 'Landmine Press',
        alias: ['landmine press', 'press mina'],
        grupoMuscular: 'hombros',
        musculosSecundarios: ['pecho', 'core'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Seguro para hombros, gran activación.',
        popularidad: 76,
        orden: 73,
        activo: true
    },
    {
        id: 'upright_row',
        nombre: 'Remo al mentón',
        nombreEN: 'Upright Row',
        alias: ['upright row', 'remo vertical', 'remo barbilla'],
        grupoMuscular: 'hombros',
        musculosSecundarios: ['trapecio'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Deltoides y trapecio superior.',
        popularidad: 72,
        orden: 74,
        activo: true
    },
    {
        id: 'elevaciones_w',
        nombre: 'Elevaciones en W',
        nombreEN: 'W Raises',
        alias: ['w raises', 'deltoides posterior w'],
        grupoMuscular: 'hombros',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Aislamiento de deltoides posterior.',
        popularidad: 68,
        orden: 75,
        activo: true
    },
    // ========== ADICIONALES BRAZOS (8) ==========
    {
        id: 'curl_martillo',
        nombre: 'Curl martillo',
        nombreEN: 'Hammer Curl',
        alias: ['hammer curl', 'curl neutro'],
        grupoMuscular: 'biceps',
        musculosSecundarios: ['antebrazos'],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Desarrollo de braquial y antebrazos.',
        popularidad: 87,
        orden: 76,
        activo: true
    },
    {
        id: 'curl_concentrado',
        nombre: 'Curl concentrado',
        nombreEN: 'Concentration Curl',
        alias: ['concentration curl', 'curl concéntrico'],
        grupoMuscular: 'biceps',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Máximo aislamiento de bíceps.',
        popularidad: 78,
        orden: 77,
        activo: true
    },
    {
        id: 'curl_predicador',
        nombre: 'Curl predicador',
        nombreEN: 'Preacher Curl',
        alias: ['preacher curl', 'curl scott'],
        grupoMuscular: 'biceps',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Aislamiento estricto de bíceps.',
        popularidad: 81,
        orden: 78,
        activo: true
    },
    {
        id: 'curl_21s',
        nombre: 'Curl 21s',
        nombreEN: '21 Curls',
        alias: ['21 curls', 'curl veintiuno'],
        grupoMuscular: 'biceps',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'barra',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '💪',
        descripcion: '7+7+7 para congestión máxima.',
        popularidad: 74,
        orden: 79,
        activo: true
    },
    {
        id: 'press_cerrado_barra',
        nombre: 'Press banca agarre cerrado',
        nombreEN: 'Close Grip Bench Press',
        alias: ['close grip bench', 'press cerrado'],
        grupoMuscular: 'triceps',
        musculosSecundarios: ['pecho'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Masa y fuerza en tríceps.',
        popularidad: 86,
        orden: 80,
        activo: true
    },
    {
        id: 'fondos_triceps_maquina',
        nombre: 'Fondos tríceps en máquina',
        nombreEN: 'Machine Triceps Dips',
        alias: ['dips máquina', 'fondos máquina'],
        grupoMuscular: 'triceps',
        musculosSecundarios: [],
        tipo: 'compuesto',
        equipamiento: 'maquina',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Seguro para principiantes.',
        popularidad: 73,
        orden: 81,
        activo: true
    },
    {
        id: 'overhead_extension_cuerda',
        nombre: 'Extensión overhead con cuerda',
        nombreEN: 'Overhead Rope Extension',
        alias: ['extensión sobre cabeza cuerda', 'rope overhead'],
        grupoMuscular: 'triceps',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'cable',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Cabeza larga del tríceps.',
        popularidad: 79,
        orden: 82,
        activo: true
    },
    {
        id: 'kickbacks',
        nombre: 'Kickbacks con mancuerna',
        nombreEN: 'Dumbbell Kickbacks',
        alias: ['kickback', 'patada trasera tríceps'],
        grupoMuscular: 'triceps',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '💪',
        descripcion: 'Definición de tríceps.',
        popularidad: 70,
        orden: 83,
        activo: true
    },
    // ========== ADICIONALES CORE (7) ==========
    {
        id: 'ab_wheel',
        nombre: 'Rueda abdominal',
        nombreEN: 'Ab Wheel Rollout',
        alias: ['ab wheel', 'rueda ab', 'rollout'],
        grupoMuscular: 'core',
        musculosSecundarios: ['hombros'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'estatico',
        dificultad: 'avanzado',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🔥',
        descripcion: 'Ejercicio avanzado para core completo.',
        popularidad: 84,
        orden: 84,
        activo: true
    },
    {
        id: 'pallof_press',
        nombre: 'Pallof press',
        nombreEN: 'Pallof Press',
        alias: ['pallof', 'anti-rotación'],
        grupoMuscular: 'core',
        musculosSecundarios: [],
        tipo: 'estatico',
        equipamiento: 'cable',
        mecanica: 'estatico',
        dificultad: 'intermedio',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🔥',
        descripcion: 'Anti-rotación para estabilidad.',
        popularidad: 75,
        orden: 85,
        activo: true
    },
    {
        id: 'russian_twist',
        nombre: 'Russian twist',
        nombreEN: 'Russian Twist',
        alias: ['russian twist', 'giro ruso'],
        grupoMuscular: 'core',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'peso_corporal',
        mecanica: 'estatico',
        dificultad: 'principiante',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🔥',
        descripcion: 'Oblicuos y rotación.',
        popularidad: 80,
        orden: 86,
        activo: true
    },
    {
        id: 'dragon_flag',
        nombre: 'Dragon flag',
        nombreEN: 'Dragon Flag',
        alias: ['bandera dragón', 'dragon flag'],
        grupoMuscular: 'core',
        musculosSecundarios: [],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'estatico',
        dificultad: 'avanzado',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🔥',
        descripcion: 'Ejercicio avanzado de Bruce Lee.',
        popularidad: 68,
        orden: 87,
        activo: true
    },
    {
        id: 'cable_crunch',
        nombre: 'Cable crunch',
        nombreEN: 'Cable Crunch',
        alias: ['crunch cable', 'crunch polea'],
        grupoMuscular: 'core',
        musculosSecundarios: [],
        tipo: 'aislamiento',
        equipamiento: 'cable',
        mecanica: 'estatico',
        dificultad: 'principiante',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🔥',
        descripcion: 'Sobrecarga progresiva en abdominales.',
        popularidad: 77,
        orden: 88,
        activo: true
    },
    {
        id: 'side_plank',
        nombre: 'Plancha lateral',
        nombreEN: 'Side Plank',
        alias: ['side plank', 'plank lateral'],
        grupoMuscular: 'core',
        musculosSecundarios: [],
        tipo: 'estatico',
        equipamiento: 'peso_corporal',
        mecanica: 'estatico',
        dificultad: 'principiante',
        tipoMedicion: 'tiempo',
        unidadPeso: 'segundos',
        icono: '🔥',
        descripcion: 'Fortalecimiento de oblicuos.',
        popularidad: 82,
        orden: 89,
        activo: true
    },
    {
        id: 'toes_to_bar',
        nombre: 'Toes to bar',
        nombreEN: 'Toes to Bar',
        alias: ['ttb', 'dedos a barra'],
        grupoMuscular: 'core',
        musculosSecundarios: [],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'estatico',
        dificultad: 'avanzado',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🔥',
        descripcion: 'Core completo y flexores de cadera.',
        popularidad: 73,
        orden: 90,
        activo: true
    },
    // ========== ADICIONALES FULLBODY (10) ==========
    {
        id: 'clean_and_press',
        nombre: 'Clean and press',
        nombreEN: 'Clean and Press',
        alias: ['cargada y press', 'power clean press'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['hombros', 'piernas'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'avanzado',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏋️',
        descripcion: 'Ejercicio olímpico para potencia total.',
        popularidad: 80,
        orden: 91,
        activo: true
    },
    {
        id: 'snatch',
        nombre: 'Snatch (arrancada)',
        nombreEN: 'Snatch',
        alias: ['arrancada', 'snatch olímpico'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['hombros', 'espalda'],
        tipo: 'compuesto',
        equipamiento: 'barra',
        mecanica: 'empuje',
        dificultad: 'avanzado',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏋️',
        descripcion: 'Levantamiento olímpico técnico.',
        popularidad: 72,
        orden: 92,
        activo: true
    },
    {
        id: 'kettlebell_turkish_getup',
        nombre: 'Turkish get-up',
        nombreEN: 'Turkish Get-Up',
        alias: ['turkish getup', 'tgu', 'levantamiento turco'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['core', 'hombros'],
        tipo: 'compuesto',
        equipamiento: 'mancuerna',
        mecanica: 'empuje',
        dificultad: 'avanzado',
        tipoMedicion: 'peso_reps',
        unidadPeso: 'kg',
        icono: '🏋️',
        descripcion: 'Movimiento funcional completo.',
        popularidad: 68,
        orden: 93,
        activo: true
    },
    {
        id: 'wall_ball',
        nombre: 'Wall ball',
        nombreEN: 'Wall Ball',
        alias: ['wall ball', 'lanzamiento pared'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['piernas', 'hombros'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🏋️',
        descripcion: 'CrossFit clásico, acondicionamiento.',
        popularidad: 76,
        orden: 94,
        activo: true
    },
    {
        id: 'rope_climb',
        nombre: 'Escalada de cuerda',
        nombreEN: 'Rope Climb',
        alias: ['rope climb', 'trepar cuerda'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['espalda', 'biceps'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'traccion',
        dificultad: 'avanzado',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🏋️',
        descripcion: 'Fuerza funcional total.',
        popularidad: 65,
        orden: 95,
        activo: true
    },
    {
        id: 'box_jumps',
        nombre: 'Box jumps',
        nombreEN: 'Box Jumps',
        alias: ['saltos cajón', 'box jump'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['piernas'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'reps',
        unidadPeso: 'repeticiones',
        icono: '🏋️',
        descripcion: 'Potencia explosiva de piernas.',
        popularidad: 81,
        orden: 96,
        activo: true
    },
    {
        id: 'battle_ropes',
        nombre: 'Battle ropes',
        nombreEN: 'Battle Ropes',
        alias: ['cuerdas batalla', 'battling ropes'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['core', 'hombros'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'tiempo',
        unidadPeso: 'segundos',
        icono: '🏋️',
        descripcion: 'Acondicionamiento y resistencia.',
        popularidad: 74,
        orden: 97,
        activo: true
    },
    {
        id: 'sled_push',
        nombre: 'Empuje de trineo',
        nombreEN: 'Sled Push',
        alias: ['sled push', 'trineo empuje'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['piernas', 'core'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'distancia',
        unidadPeso: 'metros',
        icono: '🏋️',
        descripcion: 'Potencia y acondicionamiento.',
        popularidad: 78,
        orden: 98,
        activo: true
    },
    {
        id: 'sled_pull',
        nombre: 'Arrastre de trineo',
        nombreEN: 'Sled Pull',
        alias: ['sled pull', 'trineo arrastre'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: ['espalda', 'piernas'],
        tipo: 'compuesto',
        equipamiento: 'peso_corporal',
        mecanica: 'traccion',
        dificultad: 'intermedio',
        tipoMedicion: 'distancia',
        unidadPeso: 'metros',
        icono: '🏋️',
        descripcion: 'Cadena posterior y acondicionamiento.',
        popularidad: 75,
        orden: 99,
        activo: true
    },
    {
        id: 'assault_bike',
        nombre: 'Assault bike',
        nombreEN: 'Assault Bike',
        alias: ['assault bike', 'air bike', 'bici aire'],
        grupoMuscular: 'fullbody',
        musculosSecundarios: [],
        tipo: 'compuesto',
        equipamiento: 'maquina',
        mecanica: 'empuje',
        dificultad: 'intermedio',
        tipoMedicion: 'calorias',
        unidadPeso: 'kcal',
        icono: '🚴',
        descripcion: 'Cardio de alta intensidad.',
        popularidad: 79,
        orden: 100,
        activo: true
    }
];

// =========================================
// FUNCIONES DE INICIALIZACIÓN
// =========================================

/**
 * Inicializar ejercicios en Firestore (ejecutar solo una vez)
 * Sube los 50 ejercicios a la colección 'exercises'
 */
export async function inicializarEjerciciosEnFirestore() {
    try {
        console.log('🏋️ Inicializando base de datos de ejercicios en Firestore...');
        
        const exercisesRef = collection(db, 'exercises');
        let contador = 0;
        
        for (const exercise of EXERCISES_DB) {
            await setDoc(doc(exercisesRef, exercise.id), exercise);
            contador++;
            console.log(`✅ ${contador}/${EXERCISES_DB.length}: ${exercise.nombre}`);
        }
        
        console.log(`🎉 ¡${contador} ejercicios inicializados correctamente!`);
        return { success: true, count: contador };
    } catch (error) {
        console.error('❌ Error al inicializar ejercicios:', error);
        throw error;
    }
}

/**
 * Verificar si los ejercicios ya están inicializados
 */
export async function ejerciciosYaInicializados() {
    try {
        const exercisesRef = collection(db, 'exercises');
        const snapshot = await getDocs(exercisesRef);
        return snapshot.size >= 50;
    } catch (error) {
        console.error('Error al verificar ejercicios:', error);
        return false;
    }
}

// =========================================
// FUNCIONES DE CONSULTA
// =========================================

/**
 * Obtener todos los ejercicios (con cache)
 */
export async function obtenerEjercicios() {
    try {
        console.log('📚 Intentando cargar ejercicios de Firestore...');
        const exercisesRef = collection(db, 'exercises');
        const snapshot = await getDocs(exercisesRef);
        
        console.log('📊 Docs obtenidos de Firestore:', snapshot.size);
        
        const ejercicios = [];
        snapshot.forEach((doc) => {
            ejercicios.push({ id: doc.id, ...doc.data() });
        });
        
        // Si Firestore está vacío, usar datos locales
        if (ejercicios.length === 0) {
            console.log('⚠️ Firestore vacío, usando EXERCISES_DB local');
            console.log('📦 Ejercicios locales disponibles:', EXERCISES_DB.length);
            
            // Normalizar formato para compatibilidad
            return EXERCISES_DB.map(ej => ({
                ...ej,
                name: ej.nombre || ej.name,
                musculo: ej.grupoMuscular || ej.musculo,
                primaryMuscle: ej.grupoMuscular || ej.primaryMuscle
            }));
        }
        
        // Ordenar por popularidad y orden
        ejercicios.sort((a, b) => {
            if (b.popularidad !== a.popularidad) {
                return b.popularidad - a.popularidad;
            }
            return a.orden - b.orden;
        });
        
        console.log('✅ Ejercicios cargados de Firestore:', ejercicios.length);
        return ejercicios;
    } catch (error) {
        console.error('❌ Error al obtener ejercicios de Firestore:', error);
        console.log('📦 Fallback a EXERCISES_DB local:', EXERCISES_DB.length, 'ejercicios');
        
        // Fallback a datos locales - normalizar formato
        return EXERCISES_DB.map(ej => ({
            ...ej,
            name: ej.nombre || ej.name,
            musculo: ej.grupoMuscular || ej.musculo,
            primaryMuscle: ej.grupoMuscular || ej.primaryMuscle
        }));
    }
}

/**
 * Obtener un ejercicio por ID
 */
export async function obtenerEjercicioPorId(exerciseId) {
    try {
        const exerciseRef = doc(db, 'exercises', exerciseId);
        const exerciseSnap = await getDoc(exerciseRef);
        
        if (exerciseSnap.exists()) {
            return { id: exerciseSnap.id, ...exerciseSnap.data() };
        }
        
        // Fallback a datos locales
        return EXERCISES_DB.find(ex => ex.id === exerciseId);
    } catch (error) {
        console.error('Error al obtener ejercicio:', error);
        return EXERCISES_DB.find(ex => ex.id === exerciseId);
    }
}

/**
 * Buscar ejercicios por query y filtros
 */
export function buscarEjercicios(query = '', filtros = {}) {
    let ejercicios = [...EXERCISES_DB];
    
    // Filtrar por query (nombre, alias)
    if (query) {
        const queryLower = query.toLowerCase();
        ejercicios = ejercicios.filter(ej => {
            const nombreMatch = ej.nombre.toLowerCase().includes(queryLower);
            const nombreENMatch = ej.nombreEN.toLowerCase().includes(queryLower);
            const aliasMatch = ej.alias.some(a => a.toLowerCase().includes(queryLower));
            return nombreMatch || nombreENMatch || aliasMatch;
        });
    }
    
    // Filtrar por grupo muscular
    if (filtros.grupoMuscular) {
        ejercicios = ejercicios.filter(ej => ej.grupoMuscular === filtros.grupoMuscular);
    }
    
    // Filtrar por equipamiento
    if (filtros.equipamiento) {
        ejercicios = ejercicios.filter(ej => ej.equipamiento === filtros.equipamiento);
    }
    
    // Filtrar por tipo
    if (filtros.tipo) {
        ejercicios = ejercicios.filter(ej => ej.tipo === filtros.tipo);
    }
    
    // Filtrar por dificultad
    if (filtros.dificultad) {
        ejercicios = ejercicios.filter(ej => ej.dificultad === filtros.dificultad);
    }
    
    return ejercicios;
}

/**
 * Agrupar ejercicios por grupo muscular
 */
export function agruparEjerciciosPorGrupo(ejercicios = EXERCISES_DB) {
    const grupos = {};
    
    ejercicios.forEach(ej => {
        if (!grupos[ej.grupoMuscular]) {
            grupos[ej.grupoMuscular] = [];
        }
        grupos[ej.grupoMuscular].push(ej);
    });
    
    return grupos;
}

// =========================================
// EXPORTAR CONSTANTES
// =========================================

export const GRUPOS_MUSCULARES = [
    'pecho', 'espalda', 'piernas', 'hombros', 
    'biceps', 'triceps', 'core', 'fullbody'
];

export const EQUIPAMIENTOS = [
    'barra', 'mancuerna', 'maquina', 'cable', 'peso_corporal'
];

export const TIPOS = ['compuesto', 'aislamiento', 'estatico'];

export const DIFICULTADES = ['principiante', 'intermedio', 'avanzado'];
